name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.x
          7.0.x

    - name: Make repo pushable
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      shell: bash
      run: git remote set-url --push origin https://$GITHUB_USER:$GITHUB_PAT@github.com/$GITHUB_REPOSITORY.git

    - name: Run build script
      run: ./build.ps1 --target=Build

    - name: Get target file
      id: getfilename
      shell: bash
      run: echo "::set-output name=file::$(ls ./Harmony/bin/Release/HarmonyX*.nupkg)"

    - uses: actions/upload-artifact@v1
      with:
        path: ${{ steps.getfilename.outputs.file }}
        name: HarmonyX
